version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # against the `dev` branch
    target-branch: "dev"
